
package com.sap.document.sap.soap.functions.mc_style;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZBAPI_BUPA_ZCREATE_FROM_DATA", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ChangeBusinessAgreementObjectFactory.class
})
public interface ZBAPIBUPAZCREATEFROMDATA {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.sap.document.sap.soap.functions.mc_style.ZbapiBupaCreateFromDataResponse
     */
    @WebMethod(operationName = "ZbapiBupaCreateFromData", action = "urn:sap-com:document:sap:soap:functions:mc-style:ZBAPI_BUPA_ZCREATE_FROM_DATA:ZbapiBupaCreateFromDataRequest")
    @WebResult(name = "ZbapiBupaCreateFromDataResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", partName = "parameter")
    public ZbapiBupaCreateFromDataResponse zbapiBupaCreateFromData(
        @WebParam(name = "ZbapiBupaCreateFromData", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", partName = "parameters")
        ZbapiBupaCreateFromData parameters);

}
