
package com.sap.document.sap.soap.functions.mc_style;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZBAPI_BUPA_ZCREATE_FROM_DATA", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "file:/C:/Users/i321630/Desktop/ws/WS_ZBP_CREATE.WSDL")
public class ZBAPIBUPAZCREATEFROMDATA_Service
    extends Service
{

    private final static URL ZBAPIBUPAZCREATEFROMDATA_WSDL_LOCATION;
    private final static WebServiceException ZBAPIBUPAZCREATEFROMDATA_EXCEPTION;
    private final static QName ZBAPIBUPAZCREATEFROMDATA_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZBAPI_BUPA_ZCREATE_FROM_DATA");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/i321630/Desktop/ws/WS_ZBP_CREATE.WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZBAPIBUPAZCREATEFROMDATA_WSDL_LOCATION = url;
        ZBAPIBUPAZCREATEFROMDATA_EXCEPTION = e;
    }

    public ZBAPIBUPAZCREATEFROMDATA_Service() {
        super(__getWsdlLocation(), ZBAPIBUPAZCREATEFROMDATA_QNAME);
    }

    public ZBAPIBUPAZCREATEFROMDATA_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZBAPIBUPAZCREATEFROMDATA_QNAME, features);
    }

    public ZBAPIBUPAZCREATEFROMDATA_Service(URL wsdlLocation) {
        super(wsdlLocation, ZBAPIBUPAZCREATEFROMDATA_QNAME);
    }

    public ZBAPIBUPAZCREATEFROMDATA_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZBAPIBUPAZCREATEFROMDATA_QNAME, features);
    }

    public ZBAPIBUPAZCREATEFROMDATA_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZBAPIBUPAZCREATEFROMDATA_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZBAPIBUPAZCREATEFROMDATA
     */
    @WebEndpoint(name = "ZBupaCreateBinding")
    public ZBAPIBUPAZCREATEFROMDATA getZBupaCreateBinding() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZBupaCreateBinding"), ZBAPIBUPAZCREATEFROMDATA.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZBAPIBUPAZCREATEFROMDATA
     */
    @WebEndpoint(name = "ZBupaCreateBinding")
    public ZBAPIBUPAZCREATEFROMDATA getZBupaCreateBinding(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZBupaCreateBinding"), ZBAPIBUPAZCREATEFROMDATA.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZBAPIBUPAZCREATEFROMDATA_EXCEPTION!= null) {
            throw ZBAPIBUPAZCREATEFROMDATA_EXCEPTION;
        }
        return ZBAPIBUPAZCREATEFROMDATA_WSDL_LOCATION;
    }

}
