
package com.sap.document.sap.soap.functions.mc_style;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZCRM_WS_ZORDER_CREATE", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "classpath:/../resources/ybillingintegration/wsdl/WS_ZORDER_CREATE.WSDL")
public class ZCRMWSZORDERCREATE_Service
    extends Service
{

    private final static URL ZCRMWSZORDERCREATE_WSDL_LOCATION;
    private final static WebServiceException ZCRMWSZORDERCREATE_EXCEPTION;
    private final static QName ZCRMWSZORDERCREATE_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZCRM_WS_ZORDER_CREATE");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("classpath:/../resources/ybillingintegration/wsdl/WS_ZORDER_CREATE.WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZCRMWSZORDERCREATE_WSDL_LOCATION = url;
        ZCRMWSZORDERCREATE_EXCEPTION = e;
    }

    public ZCRMWSZORDERCREATE_Service() {
        super(__getWsdlLocation(), ZCRMWSZORDERCREATE_QNAME);
    }

    public ZCRMWSZORDERCREATE_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZCRMWSZORDERCREATE_QNAME, features);
    }

    public ZCRMWSZORDERCREATE_Service(URL wsdlLocation) {
        super(wsdlLocation, ZCRMWSZORDERCREATE_QNAME);
    }

    public ZCRMWSZORDERCREATE_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZCRMWSZORDERCREATE_QNAME, features);
    }

    public ZCRMWSZORDERCREATE_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZCRMWSZORDERCREATE_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZCRMWSZORDERCREATE
     */
    @WebEndpoint(name = "ZOrderCreateBinding2")
    public ZCRMWSZORDERCREATE getZOrderCreateBinding2() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZOrderCreateBinding2"), ZCRMWSZORDERCREATE.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZCRMWSZORDERCREATE
     */
    @WebEndpoint(name = "ZOrderCreateBinding2")
    public ZCRMWSZORDERCREATE getZOrderCreateBinding2(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZOrderCreateBinding2"), ZCRMWSZORDERCREATE.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZCRMWSZORDERCREATE_EXCEPTION!= null) {
            throw ZCRMWSZORDERCREATE_EXCEPTION;
        }
        return ZCRMWSZORDERCREATE_WSDL_LOCATION;
    }

}
