
package com.sap.document.sap.soap.functions.mc_style;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035 Generated source version: 2.2
 *
 */
@WebServiceClient(name = "ZCRM_WS_BUAG_CREATE", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "classpath:/../resources/ybillingintegration/wsdl/WS_ZBUAG_CREATE.WSDL")
public class ZCRMWSBUAGCREATE_Service extends Service
{

	private final static URL ZCRMWSBUAGCREATE_WSDL_LOCATION;
	private final static WebServiceException ZCRMWSBUAGCREATE_EXCEPTION;
	private final static QName ZCRMWSBUAGCREATE_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style",
			"ZCRM_WS_BUAG_CREATE");

	static
	{
		URL url = null;
		WebServiceException e = null;
		try
		{
			url = new URL("classpath:/../resources/ybillingintegration/wsdl/WS_ZBUAG_CREATE.WSDL");
		}
		catch (final MalformedURLException ex)
		{
			e = new WebServiceException(ex);
		}
		ZCRMWSBUAGCREATE_WSDL_LOCATION = url;
		ZCRMWSBUAGCREATE_EXCEPTION = e;
	}

	public ZCRMWSBUAGCREATE_Service()
	{
		super(__getWsdlLocation(), ZCRMWSBUAGCREATE_QNAME);
	}

	public ZCRMWSBUAGCREATE_Service(final WebServiceFeature... features)
	{
		super(__getWsdlLocation(), ZCRMWSBUAGCREATE_QNAME, features);
	}

	public ZCRMWSBUAGCREATE_Service(final URL wsdlLocation)
	{
		super(wsdlLocation, ZCRMWSBUAGCREATE_QNAME);
	}

	public ZCRMWSBUAGCREATE_Service(final URL wsdlLocation, final WebServiceFeature... features)
	{
		super(wsdlLocation, ZCRMWSBUAGCREATE_QNAME, features);
	}

	public ZCRMWSBUAGCREATE_Service(final URL wsdlLocation, final QName serviceName)
	{
		super(wsdlLocation, serviceName);
	}

	public ZCRMWSBUAGCREATE_Service(final URL wsdlLocation, final QName serviceName, final WebServiceFeature... features)
	{
		super(wsdlLocation, serviceName, features);
	}

	/**
	 *
	 * @return returns ZCRMWSBUAGCREATE
	 */
	@WebEndpoint(name = "ZBuAG_Create_Binding")
	public ZCRMWSBUAGCREATE getZBuAGCreateBinding()
	{
		return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZBuAG_Create_Binding"),
				ZCRMWSBUAGCREATE.class);
	}

	/**
	 *
	 * @param features
	 *           A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in
	 *           the <code>features</code> parameter will have their default values.
	 * @return returns ZCRMWSBUAGCREATE
	 */
	@WebEndpoint(name = "ZBuAG_Create_Binding")
	public ZCRMWSBUAGCREATE getZBuAGCreateBinding(final WebServiceFeature... features)
	{
		return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZBuAG_Create_Binding"),
				ZCRMWSBUAGCREATE.class, features);
	}

	private static URL __getWsdlLocation()
	{
		if (ZCRMWSBUAGCREATE_EXCEPTION != null)
		{
			throw ZCRMWSBUAGCREATE_EXCEPTION;
		}
		return ZCRMWSBUAGCREATE_WSDL_LOCATION;
	}

}
