
package com.sap.document.sap.soap.functions.mc_style;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZCRM_WS_BUPA_PCARD_ADD", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "file:/C:/Users/i321630/Desktop/ws/WS_ZBUPA_PCARD_ADD.WSDL")
public class ZCRMWSBUPAPCARDADD_Service
    extends Service
{

    private final static URL ZCRMWSBUPAPCARDADD_WSDL_LOCATION;
    private final static WebServiceException ZCRMWSBUPAPCARDADD_EXCEPTION;
    private final static QName ZCRMWSBUPAPCARDADD_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZCRM_WS_BUPA_PCARD_ADD");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/i321630/Desktop/ws/WS_ZBUPA_PCARD_ADD.WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZCRMWSBUPAPCARDADD_WSDL_LOCATION = url;
        ZCRMWSBUPAPCARDADD_EXCEPTION = e;
    }

    public ZCRMWSBUPAPCARDADD_Service() {
        super(__getWsdlLocation(), ZCRMWSBUPAPCARDADD_QNAME);
    }

    public ZCRMWSBUPAPCARDADD_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZCRMWSBUPAPCARDADD_QNAME, features);
    }

    public ZCRMWSBUPAPCARDADD_Service(URL wsdlLocation) {
        super(wsdlLocation, ZCRMWSBUPAPCARDADD_QNAME);
    }

    public ZCRMWSBUPAPCARDADD_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZCRMWSBUPAPCARDADD_QNAME, features);
    }

    public ZCRMWSBUPAPCARDADD_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZCRMWSBUPAPCARDADD_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZCRMWSBUPAPCARDADD
     */
    @WebEndpoint(name = "ZBupaPCardAddBinding")
    public ZCRMWSBUPAPCARDADD getZBupaPCardAddBinding() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZBupaPCardAddBinding"), ZCRMWSBUPAPCARDADD.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZCRMWSBUPAPCARDADD
     */
    @WebEndpoint(name = "ZBupaPCardAddBinding")
    public ZCRMWSBUPAPCARDADD getZBupaPCardAddBinding(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZBupaPCardAddBinding"), ZCRMWSBUPAPCARDADD.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZCRMWSBUPAPCARDADD_EXCEPTION!= null) {
            throw ZCRMWSBUPAPCARDADD_EXCEPTION;
        }
        return ZCRMWSBUPAPCARDADD_WSDL_LOCATION;
    }

}
