
package com.sap.document.sap.soap.functions.mc_style;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZCRM_WS_BAPI_BUPA_FRG0030_ADD", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "file:/C:/Users/i321630/Desktop/ws/WS_ZBP_FRG0030_ADD.WSDL")
public class ZCRMWSBAPIBUPAFRG0030ADD_Service
    extends Service
{

    private final static URL ZCRMWSBAPIBUPAFRG0030ADD_WSDL_LOCATION;
    private final static WebServiceException ZCRMWSBAPIBUPAFRG0030ADD_EXCEPTION;
    private final static QName ZCRMWSBAPIBUPAFRG0030ADD_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZCRM_WS_BAPI_BUPA_FRG0030_ADD");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/i321630/Desktop/ws/WS_ZBP_FRG0030_ADD.WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZCRMWSBAPIBUPAFRG0030ADD_WSDL_LOCATION = url;
        ZCRMWSBAPIBUPAFRG0030ADD_EXCEPTION = e;
    }

    public ZCRMWSBAPIBUPAFRG0030ADD_Service() {
        super(__getWsdlLocation(), ZCRMWSBAPIBUPAFRG0030ADD_QNAME);
    }

    public ZCRMWSBAPIBUPAFRG0030ADD_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZCRMWSBAPIBUPAFRG0030ADD_QNAME, features);
    }

    public ZCRMWSBAPIBUPAFRG0030ADD_Service(URL wsdlLocation) {
        super(wsdlLocation, ZCRMWSBAPIBUPAFRG0030ADD_QNAME);
    }

    public ZCRMWSBAPIBUPAFRG0030ADD_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZCRMWSBAPIBUPAFRG0030ADD_QNAME, features);
    }

    public ZCRMWSBAPIBUPAFRG0030ADD_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZCRMWSBAPIBUPAFRG0030ADD_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZCRMWSBAPIBUPAFRG0030ADD
     */
    @WebEndpoint(name = "ZBupaFRG0030AddBinding")
    public ZCRMWSBAPIBUPAFRG0030ADD getZBupaFRG0030AddBinding() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZBupaFRG0030AddBinding"), ZCRMWSBAPIBUPAFRG0030ADD.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZCRMWSBAPIBUPAFRG0030ADD
     */
    @WebEndpoint(name = "ZBupaFRG0030AddBinding")
    public ZCRMWSBAPIBUPAFRG0030ADD getZBupaFRG0030AddBinding(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZBupaFRG0030AddBinding"), ZCRMWSBAPIBUPAFRG0030ADD.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZCRMWSBAPIBUPAFRG0030ADD_EXCEPTION!= null) {
            throw ZCRMWSBAPIBUPAFRG0030ADD_EXCEPTION;
        }
        return ZCRMWSBAPIBUPAFRG0030ADD_WSDL_LOCATION;
    }

}
