
package com.sap.document.sap.soap.functions.mc_style;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZCRM_WS_BUPA_PCARD_ADD", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    CreatePaymentCardObjectFactory.class
})
public interface ZCRMWSBUPAPCARDADD {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.sap.document.sap.soap.functions.mc_style.ZbapiBupaPcardAddResponse
     */
    @WebMethod(operationName = "ZbapiBupaPcardAdd", action = "urn:sap-com:document:sap:soap:functions:mc-style:ZCRM_WS_BUPA_PCARD_ADD:ZbapiBupaPcardAddRequest")
    @WebResult(name = "ZbapiBupaPcardAddResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", partName = "parameter")
    public ZbapiBupaPcardAddResponse zbapiBupaPcardAdd(
        @WebParam(name = "ZbapiBupaPcardAdd", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", partName = "parameters")
        ZbapiBupaPcardAdd parameters);

}
