
package com.sap.document.sap.soap.functions.mc_style;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZCRM_WS_BUAG_CHANGE", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "classpath:/ybillingintegration/wsdl/WS_ZBUAG_CHANGE.WSDL")
public class ZCRMWSBUAGCHANGE_Service
    extends Service
{

    private final static URL ZCRMWSBUAGCHANGE_WSDL_LOCATION;
    private final static WebServiceException ZCRMWSBUAGCHANGE_EXCEPTION;
    private final static QName ZCRMWSBUAGCHANGE_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZCRM_WS_BUAG_CHANGE");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("classpath:/ybillingintegration/wsdl/WS_ZBUAG_CHANGE.WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZCRMWSBUAGCHANGE_WSDL_LOCATION = url;
        ZCRMWSBUAGCHANGE_EXCEPTION = e;
    }

    public ZCRMWSBUAGCHANGE_Service() {
        super(__getWsdlLocation(), ZCRMWSBUAGCHANGE_QNAME);
    }

    public ZCRMWSBUAGCHANGE_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZCRMWSBUAGCHANGE_QNAME, features);
    }

    public ZCRMWSBUAGCHANGE_Service(URL wsdlLocation) {
        super(wsdlLocation, ZCRMWSBUAGCHANGE_QNAME);
    }

    public ZCRMWSBUAGCHANGE_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZCRMWSBUAGCHANGE_QNAME, features);
    }

    public ZCRMWSBUAGCHANGE_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZCRMWSBUAGCHANGE_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZCRMWSBUAGCHANGE
     */
    @WebEndpoint(name = "ZBuagChangeBinding")
    public ZCRMWSBUAGCHANGE getZBuagChangeBinding() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZBuagChangeBinding"), ZCRMWSBUAGCHANGE.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZCRMWSBUAGCHANGE
     */
    @WebEndpoint(name = "ZBuagChangeBinding")
    public ZCRMWSBUAGCHANGE getZBuagChangeBinding(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZBuagChangeBinding"), ZCRMWSBUAGCHANGE.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZCRMWSBUAGCHANGE_EXCEPTION!= null) {
            throw ZCRMWSBUAGCHANGE_EXCEPTION;
        }
        return ZCRMWSBUAGCHANGE_WSDL_LOCATION;
    }

}
