
package com.sap.document.sap.soap.functions.mc_style;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZCRM_WS_BUPA_ORD_HIST_DETAILS", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "classpath:/ybillingintegration/wsdl/WS_ZBUPA_ORD_HIST_DETAILS.WSDL")
public class ZCRMWSBUPAORDHISTDETAILS_Service
    extends Service
{

    private final static URL ZCRMWSBUPAORDHISTDETAILS_WSDL_LOCATION;
    private final static WebServiceException ZCRMWSBUPAORDHISTDETAILS_EXCEPTION;
    private final static QName ZCRMWSBUPAORDHISTDETAILS_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZCRM_WS_BUPA_ORD_HIST_DETAILS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("classpath:/ybillingintegration/wsdl/WS_ZBUPA_ORD_HIST_DETAILS.WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZCRMWSBUPAORDHISTDETAILS_WSDL_LOCATION = url;
        ZCRMWSBUPAORDHISTDETAILS_EXCEPTION = e;
    }

    public ZCRMWSBUPAORDHISTDETAILS_Service() {
        super(__getWsdlLocation(), ZCRMWSBUPAORDHISTDETAILS_QNAME);
    }

    public ZCRMWSBUPAORDHISTDETAILS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZCRMWSBUPAORDHISTDETAILS_QNAME, features);
    }

    public ZCRMWSBUPAORDHISTDETAILS_Service(URL wsdlLocation) {
        super(wsdlLocation, ZCRMWSBUPAORDHISTDETAILS_QNAME);
    }

    public ZCRMWSBUPAORDHISTDETAILS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZCRMWSBUPAORDHISTDETAILS_QNAME, features);
    }

    public ZCRMWSBUPAORDHISTDETAILS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZCRMWSBUPAORDHISTDETAILS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZCRMWSBUPAORDHISTDETAILS
     */
    @WebEndpoint(name = "ZBupaOrdHistBinding")
    public ZCRMWSBUPAORDHISTDETAILS getZBupaOrdHistBinding() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZBupaOrdHistBinding"), ZCRMWSBUPAORDHISTDETAILS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZCRMWSBUPAORDHISTDETAILS
     */
    @WebEndpoint(name = "ZBupaOrdHistBinding")
    public ZCRMWSBUPAORDHISTDETAILS getZBupaOrdHistBinding(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZBupaOrdHistBinding"), ZCRMWSBUPAORDHISTDETAILS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZCRMWSBUPAORDHISTDETAILS_EXCEPTION!= null) {
            throw ZCRMWSBUPAORDHISTDETAILS_EXCEPTION;
        }
        return ZCRMWSBUPAORDHISTDETAILS_WSDL_LOCATION;
    }

}
