
package com.sap.document.sap.soap.functions.mc_style;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZCRM_WS_BUAG_CREATE", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    CreateBusinessAgreementObjectFactory.class
})
public interface ZCRMWSBUAGCREATE {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.sap.document.sap.soap.functions.mc_style.ZcrmBuagCreateResponse
     * @throws ZcrmBuagCreateException
     */
    @WebMethod(operationName = "ZcrmBuagCreate", action = "urn:sap-com:document:sap:soap:functions:mc-style:ZCRM_WS_BUAG_CREATE:ZcrmBuagCreateRequest")
    @WebResult(name = "ZcrmBuagCreateResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", partName = "parameter")
    public ZcrmBuagCreateResponse zcrmBuagCreate(
        @WebParam(name = "ZcrmBuagCreate", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", partName = "parameters")
        ZcrmBuagCreate parameters)
        throws ZcrmBuagCreateException
    ;

}
