
package com.sap.document.sap.soap.functions.mc_style;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ZcrmBuagCreate.Exception", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
public class ZcrmBuagCreateException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ZcrmBuagCreateRfcException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ZcrmBuagCreateException(String message, ZcrmBuagCreateRfcException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ZcrmBuagCreateException(String message, ZcrmBuagCreateRfcException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.sap.document.sap.soap.functions.mc_style.ZcrmBuagCreateRfcException
     */
    public ZcrmBuagCreateRfcException getFaultInfo() {
        return faultInfo;
    }

}
