
package com.sap.document.sap.soap.functions.mc_style;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZCRM_WS_BUAG_CHANGE", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ChangeBusinessAgreementObjectFactory.class
})
public interface ZCRMWSBUAGCHANGE {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.sap.document.sap.soap.functions.mc_style.ZcrmBuagChangeResponse
     */
    @WebMethod(operationName = "ZcrmBuagChange", action = "urn:sap-com:document:sap:soap:functions:mc-style:ZCRM_WS_BUAG_CHANGE:ZcrmBuagChangeRequest")
    @WebResult(name = "ZcrmBuagChangeResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", partName = "parameter")
    public ZcrmBuagChangeResponse zcrmBuagChange(
        @WebParam(name = "ZcrmBuagChange", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", partName = "parameters")
        ZcrmBuagChange parameters);

}
