/**
 *
 */
package com.hybris.showcase.events.interaction;

/**
 * @author marius.bogdan.ionescu@sap.com
 *
 */
public interface EventProps
{
	String CUSTOMER = "CUSTOMER";
	String INITIATIVE_CATEGORY_ID = "INITIATIVE_CATEGORY_ID";

	String INTERACTION_CUSTOMER_ID = "INTERACTION_CUSTOMER_ID";
	String INTERACTION_ID_ORIGIN = "INTERACTION_ID_ORIGIN";
	String INTERACTION_COMM_MEDIUM = "INTERACTION_COMM_MEDIUM";
	String INTERACTION_INITIATIVE_ID = "INTERACTION_INITIATIVE_ID";
	String INTERACTION_INTERACTION_TYPE = "INTERACTION_INTERACTION_TYPE";
	String INTERACTION_SOURCE_DATA_URL = "INTERACTION_SOURCE_DATA_URL";
	String INTERACTION_SOURCE_OBJECT_ID = "INTERACTION_SOURCE_OBJECT_ID";
	String INTERACTION_CONTENT_TITLE = "INTERACTION_CONTENT_TITLE";
	String INTERACTION_CONTENT_DATA = "INTERACTION_CONTENT_DATA";
	String INTERACTION_VALUATION = "INTERACTION_VALUATION";
	String INTEREST_ITEM = "INTEREST_ITEM";
}
