
package com.hybris.mb2bshowcase.c4cintegration.ws.servicesshowcase;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ManageServiceRequestIn", targetNamespace = "http://sap.com/xi/A1S/Global")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ManageServiceRequestIn {


    /**
     * 
     * @param serviceRequestBundleMaintainRequest2Sync
     * @return
     *     returns ServiceRequestMaintainConfirmationBundleMessageSync
     * @throws StandardFaultMessage_Exception
     */
    @WebMethod(operationName = "MaintainBundle", action = "http://sap.com/xi/A1S/Global/ManageServiceRequestIn/MaintainBundleRequest")
    @WebResult(name = "ServiceRequestBundleMaintainConfirmation2_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "ServiceRequestBundleMaintainConfirmation2_sync")
    public ServiceRequestMaintainConfirmationBundleMessageSync maintainBundle(
        @WebParam(name = "ServiceRequestBundleMaintainRequest2_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "ServiceRequestBundleMaintainRequest2_sync")
        ServiceRequestMaintainRequestBundleMessageSync serviceRequestBundleMaintainRequest2Sync)
        throws StandardFaultMessage_Exception
    ;

    /**
     * 
     * @param serviceRequestRequestBundleCheckMaintainQuerySync
     * @return
     *     returns ServiceRequestMaintainConfirmationBundleMessageSync
     * @throws StandardFaultMessage_Exception
     */
    @WebMethod(operationName = "CheckMaintainBundle", action = "http://sap.com/xi/A1S/Global/ManageServiceRequestIn/CheckMaintainBundleRequest")
    @WebResult(name = "ServiceRequestRequestBundleCheckMaintainResponse_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "ServiceRequestRequestBundleCheckMaintainResponse_sync")
    public ServiceRequestMaintainConfirmationBundleMessageSync checkMaintainBundle(
        @WebParam(name = "ServiceRequestRequestBundleCheckMaintainQuery_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "ServiceRequestRequestBundleCheckMaintainQuery_sync")
        ServiceRequestMaintainRequestBundleMessageSync serviceRequestRequestBundleCheckMaintainQuerySync)
        throws StandardFaultMessage_Exception
    ;

}
