
package com.hybris.mb2bshowcase.c4cintegration.ws.servicesshowcase;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "QueryServiceRequestIn", targetNamespace = "http://sap.com/xi/A1S/Global")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface QueryServiceRequestIn {


    /**
     * 
     * @param serviceRequestByElementsQuerySync
     * @return
     *     returns ServiceRequestByElementsResponseMessageSync
     * @throws StandardFaultMessage_Exception
     */
    @WebMethod(operationName = "FindByElements", action = "http://sap.com/xi/A1S/Global/QueryServiceRequestIn/FindByElementsRequest")
    @WebResult(name = "ServiceRequestByElementsResponse_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "ServiceRequestByElementsResponse_sync")
    public ServiceRequestByElementsResponseMessageSync findByElements(
        @WebParam(name = "ServiceRequestByElementsQuery_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "ServiceRequestByElementsQuery_sync")
        ServiceRequestByElementsQueryMessageSync serviceRequestByElementsQuerySync)
        throws StandardFaultMessage_Exception
    ;

}
