
package com.hybris.mb2bshowcase.c4cintegration.ws.servicesshowcase;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "StandardFaultMessage", targetNamespace = "http://sap.com/xi/AP/Common/Global")
public class StandardFaultMessage_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private StandardFaultMessage faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public StandardFaultMessage_Exception(String message, StandardFaultMessage faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public StandardFaultMessage_Exception(String message, StandardFaultMessage faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: StandardFaultMessage
     */
    public StandardFaultMessage getFaultInfo() {
        return faultInfo;
    }

}
