
package com.highdeal.ws.charging;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035 Generated source version: 2.2
 *
 */
@WebServiceClient(name = "chargeableItemCharging", targetNamespace = "http://charging.ws.highdeal.com/", wsdlLocation = "classpath:/ybillingintegration/wsdl/WS_CHARG_ITEM_CHARGING/chargeableItemCharging.wsdl")
public class ChargeableItemCharging extends Service
{

	private final static URL CHARGEABLEITEMCHARGING_WSDL_LOCATION;
	private final static WebServiceException CHARGEABLEITEMCHARGING_EXCEPTION;
	private final static QName CHARGEABLEITEMCHARGING_QNAME = new QName("http://charging.ws.highdeal.com/",
			"chargeableItemCharging");

	static
	{
		URL url = null;
		WebServiceException e = null;
		try
		{
			url = new URL("classpath:/ybillingintegration/wsdl/WS_CHARG_ITEM_CHARGING/chargeableItemCharging.wsdl");
		}
		catch (final MalformedURLException ex)
		{
			e = new WebServiceException(ex);
		}
		CHARGEABLEITEMCHARGING_WSDL_LOCATION = url;
		CHARGEABLEITEMCHARGING_EXCEPTION = e;
	}

	public ChargeableItemCharging()
	{
		super(__getWsdlLocation(), CHARGEABLEITEMCHARGING_QNAME);
	}

	public ChargeableItemCharging(final WebServiceFeature... features)
	{
		super(__getWsdlLocation(), CHARGEABLEITEMCHARGING_QNAME, features);
	}

	public ChargeableItemCharging(final URL wsdlLocation)
	{
		super(wsdlLocation, CHARGEABLEITEMCHARGING_QNAME);
	}

	public ChargeableItemCharging(final URL wsdlLocation, final WebServiceFeature... features)
	{
		super(wsdlLocation, CHARGEABLEITEMCHARGING_QNAME, features);
	}

	public ChargeableItemCharging(final URL wsdlLocation, final QName serviceName)
	{
		super(wsdlLocation, serviceName);
	}

	public ChargeableItemCharging(final URL wsdlLocation, final QName serviceName, final WebServiceFeature... features)
	{
		super(wsdlLocation, serviceName, features);
	}

	/**
	 *
	 * @return returns ChargeableItemChargingServices
	 */
	@WebEndpoint(name = "chargeableItemChargingPort")
	public ChargeableItemChargingServices getChargeableItemChargingPort()
	{
		return super.getPort(new QName("http://charging.ws.highdeal.com/", "chargeableItemChargingPort"),
				ChargeableItemChargingServices.class);
	}

	/**
	 *
	 * @param features
	 *           A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in
	 *           the <code>features</code> parameter will have their default values.
	 * @return returns ChargeableItemChargingServices
	 */
	@WebEndpoint(name = "chargeableItemChargingPort")
	public ChargeableItemChargingServices getChargeableItemChargingPort(final WebServiceFeature... features)
	{
		return super.getPort(new QName("http://charging.ws.highdeal.com/", "chargeableItemChargingPort"),
				ChargeableItemChargingServices.class, features);
	}

	private static URL __getWsdlLocation()
	{
		if (CHARGEABLEITEMCHARGING_EXCEPTION != null)
		{
			throw CHARGEABLEITEMCHARGING_EXCEPTION;
		}
		return CHARGEABLEITEMCHARGING_WSDL_LOCATION;
	}

}
